apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "sleep 5000000"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - mountPath: "/home/dags"
          name: pv-storage
          subPath: dags
        - mountPath: "/home/logs"
          name: pv-storage
          subPath: logs
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
